apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ca
  name: ca-controller
spec:
  replicas: 1
  selector:
    name: ca
  template:
    metadata:
      labels:
        name: ca
    spec:
      containers:
      - image: claritylab/lucida:v2.1
        command: ['/bin/sh', '-c']
        args: ['cd $LUCIDAROOT/calendar/ && ./gradlew run']
        name: ca
        ports:
        - containerPort: 8084
          name: thrift
